# Generated by Django 2.1.7 on 2019-05-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('text', models.TextField(default=None)),
                ('tags', models.TextField(default=None)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gthapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('tags', models.TextField(default=None)),
                ('text', models.TextField(default=None)),
                ('approved', models.BooleanField(default=False)),
                ('deployed', models.BooleanField(default=False)),
                ('post_datetime', models.DateTimeField(default=None)),
            ],
        ),
    ]
