# Generated by Django 2.1.7 on 2019-05-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('local_count', models.IntegerField(default=None, null=True)),
                ('global_count', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='footage',
            name='tags',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='footage',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='originaltag',
            name='group',
            field=models.ManyToManyField(to='gthapp.TagsGroup'),
        ),
        migrations.AddField(
            model_name='author',
            name='group',
            field=models.ManyToManyField(to='gthapp.UsersGroup'),
        ),
    ]
