# Generated by Django 2.1.7 on 2019-05-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('gthapp', '0002_auto_20190504_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagsGroup',
            new_name='OriginalTagsGroup',
        ),
    ]
