# Generated by Django 2.1.7 on 2019-05-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0005_auto_20190510_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gthapp.Key'),
        ),
    ]
