# Generated by Django 2.1.7 on 2019-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0006_auto_20190511_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='common',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
