# Generated by Django 2.1.7 on 2019-05-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0008_author_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='keys',
        ),
        migrations.AddField(
            model_name='author',
            name='key',
            field=models.ManyToManyField(blank=True, to='gthapp.Key'),
        ),
    ]
