# Generated by Django 2.1.7 on 2019-05-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0009_auto_20190511_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='url',
        ),
    ]
