# Generated by Django 2.1.7 on 2019-05-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0011_auto_20190511_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='path',
        ),
    ]
