# Generated by Django 2.1.7 on 2019-05-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0012_auto_20190511_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_datetime',
        ),
    ]
