# Generated by Django 2.1.7 on 2019-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0013_remove_post_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
