# Generated by Django 2.1.7 on 2019-05-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0015_auto_20190515_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('footages', models.ManyToManyField(blank=True, to='gthapp.Footage')),
                ('keys', models.ManyToManyField(blank=True, to='gthapp.Key')),
                ('posts', models.ManyToManyField(blank=True, to='gthapp.Post')),
                ('tags', models.ManyToManyField(blank=True, to='gthapp.Tag')),
            ],
        ),
    ]
