# Generated by Django 2.1.7 on 2019-05-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gthapp', '0016_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='footages',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keys',
        ),
        migrations.RemoveField(
            model_name='project',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
